spring.jpa.show-sql=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=none
spring.application.name=restaurant-app-api
spring.datasource.url=jdbc:mariadb://localhost:3306/raa
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
logging.level.org.hibernate.SQL=DEBUG
